AWSTemplateFormatVersion: '2010-09-09'
Description: "Create Add-New-Record-Route53 by chibiharu"

# ------------------------------------------------------------
#  Metadate
# ------------------------------------------------------------
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Parameters:
          - PJPrefix
          - HostedZoneID
          - SubDomain
          
          
# ------------------------------------------------------------
# Input Parameters
# ------------------------------------------------------------
Parameters:
  PJPrefix:
    Type: String
  HostedZoneID:
    Type: String
    Description: "Route53-Public-HostedZoneID"
    Default: '<ホストゾーンIDを指定>'
  SubDomain:
    Description: "SubDomain"
    Type: String
    Default: '<SubDomain>.<example.com>'
    
    
### Resources ###
Resources: 
# ------------------------------------------------------------
#  New Record For Route53
# ------------------------------------------------------------
### Add A Recode ###
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneID
      Comment: "Add A Record"
      Name: !Sub '${SubDomain}'
      Type: A
      AliasTarget:
        HostedZoneId: { "Fn::ImportValue": !Sub '${PJPrefix}-ALB-CanonicalHostedZoneID' }
        DNSName: { "Fn::ImportValue": !Sub '${PJPrefix}-ALB-DNSName' }