AWSTemplateFormatVersion: "2010-09-09"
Description: "Create SecurityGroup-on-EC2-ECS-Service By chibiharu"

# ------------------------------------------------------------
# Input Parameters
# ------------------------------------------------------------
Parameters:
### Project Prefix ###
  PJPrefix:
    Type: String
    

### Resources ###
Resources:
# ------------------------------------------------------------
# SecurityGroup
# ------------------------------------------------------------
### ALB Security Group ###
    ALBSG:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "https"
            GroupName: !Sub "${PJPrefix}-ALB-SG"
            VpcId: { "Fn::ImportValue": !Sub "${PJPrefix}-vpc" }
            Tags: 
                - Key: Name
                  Value: !Sub "${PJPrefix}-ALB-SG"
            SecurityGroupIngress:
              - IpProtocol: tcp
                FromPort : 80
                ToPort : 80
                CidrIp: 0.0.0.0/0
              - IpProtocol: tcp
                FromPort : 443
                ToPort : 443
                CidrIp: 0.0.0.0/0
                
### Application Security Group ###
    AppSG:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "https(from ALB)"
            GroupName: !Sub "${PJPrefix}-App-SG"
            VpcId: { "Fn::ImportValue": !Sub "${PJPrefix}-vpc" }
            Tags: 
                - Key: Name
                  Value: !Sub "${PJPrefix}-App-SG"
            SecurityGroupIngress:
              - IpProtocol: tcp
                FromPort: 32768
                ToPort: 61000
                SourceSecurityGroupId: !Ref "ALBSG"
             
                
# ------------------------------------------------------------
# Output Parameter
# ------------------------------------------------------------
Outputs:
## ALB-SG ##
    ALBSG:
        Value: !Ref ALBSG
        Export:
            Name: !Sub "${PJPrefix}-ALB-SG"
            
## App-SG ##
    AppSG:
        Value: !Ref AppSG
        Export:
            Name: !Sub "${PJPrefix}-App-SG"