AWSTemplateFormatVersion: '2010-09-09'
Description: "Launch a SorryPage-on-ALB"


# ------------------------------------------------------------
#  Metadate
# ------------------------------------------------------------
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Parameters:
          - PJPrefix
          - SubnetIDs
          - VPCID


# ------------------------------------------------------------
#  Input Parameters
# ------------------------------------------------------------
Parameters:
### Share Param ###
  PJPrefix:
    Type: "String"
  SubnetIDs:
    Type: "List<AWS::EC2::Subnet::Id>"
    Description: "Select a subnet from two or more availability-zones."
  VPCID:
    Type: "AWS::EC2::VPC::Id"
    Description: "Select at your VPC."


### Resources ###
Resources: 
# ------------------------------------------------------------
#  SecurityGroup 
# ------------------------------------------------------------
### ALB Server Security Group ###
  ALBSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "ALB-SecurityGroup"
      GroupName: !Sub "${PJPrefix}-ALB-SG"
      VpcId: !Ref VPCID
      Tags: 
        - Key: Name
          Value: !Sub "${PJPrefix}-ALB-SG"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort : 80
          ToPort : 80
          CidrIp: 0.0.0.0/0
          
          
# ------------------------------------------------------------
#  TargetGroup
# ------------------------------------------------------------
  TargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties: 
      VpcId: !Ref VPCID
      Name: !Sub "${PJPrefix}-tg"
      Protocol: HTTP
      Port: 80
      HealthCheckProtocol: HTTP
      HealthCheckPath: "/"
      HealthCheckPort: "traffic-port"
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckTimeoutSeconds: 5
      HealthCheckIntervalSeconds: 10
      Matcher: 
        HttpCode: 200
      Tags: 
        - Key: Name
          Value: !Sub "${PJPrefix}-tg"
      TargetGroupAttributes: 
        - Key: "deregistration_delay.timeout_seconds"
          Value: 300
        - Key: "stickiness.enabled"
          Value: false
        - Key: "stickiness.type"
          Value: lb_cookie
        - Key: "stickiness.lb_cookie.duration_seconds"
          Value: 86400
          
          
# ------------------------------------------------------------
#  ALB
# ------------------------------------------------------------
### ALB ###
  ALB:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: !Sub "${PJPrefix}-ALB"
      Tags:
        - Key: Name
          Value: !Sub "${PJPrefix}-ALB"
      Scheme: "internet-facing"
      LoadBalancerAttributes:
        - Key: "deletion_protection.enabled"
          Value: false
        - Key: "idle_timeout.timeout_seconds"
          Value: 60
        - Key: "access_logs.s3.enabled"
          Value: false
      SecurityGroups:
        - !Ref "ALBSG"
      Subnets: !Ref "SubnetIDs"
      
### HTTP通信のリスナー設定 ### 
  ALBListener: 
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties: 
      DefaultActions: 
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      
### 通常パターンのリスナールール ###
  ALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      Conditions:
        - Field: path-pattern
          Values:
            - '*'
      ListenerArn: !Ref ALBListener
      Priority: 1

### メンテナンスモードのリスナールール ###
  ALBListenerRule503:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: "fixed-response"
          FixedResponseConfig:
            ContentType: 'text/html'
            MessageBody: |
                <!DOCTYPE html>
                <html lang="ja">
                <head>
                <meta charset="UTF-8">
                <title>メンテナンスのお知らせ</title>
                <style>
                  html {
                    text-align: center;
                  }
                  body {
                    margin: 0;
                    padding: 0;
                    background: #eee;
                  }
                  #conainer {
                    margin: 0 auto;
                    padding: 20px;
                    width: 600px;
                    max-width: 600px;
                  }
                  h1 {
                    font-size: 2em;
                  }
                  .warn {
                    padding: 1em;
                    background: #ff7;
                  }
                  #footer {
                    text-align: center;
                  }
                </style>
                </head>

                <body>
                  <div id="container">
                    <h1>ただいまメンテナンス中です</h1>
                    <p>
                      システムアップデートのためサービスを停止しています。<br>
                      ユーザーの皆様にはご不便をおかけしますが、メンテナンス終了まで今しばらくお待ち下さい。<br>
                    </p>
                    <h2>メンテナンス期間</h2>
                    <p class="warn">
                      <strong>202x年x月x日（x） xx:xx 〜 xx月xx日（x） xx:xx</strong><br>
                    </p>
                    <h2>
                     お問い合わせ
                    </h2>
                    <p>
                      メンテナンスに関するお問い合わせは<a href="xxxxxxxx@gmail.com">xxxxxxxx@gmail.com</a>までお願いします。
                    </p>
                    <hr>
                    <div id="footer">
                      &copy; xxx.com
                    </div>
                  </div>
                </body>
                </html>
            StatusCode: 503
      Conditions:
        - Field: path-pattern
          Values:
            - '*'
      ListenerArn: !Ref ALBListener
      Priority: 2