AWSTemplateFormatVersion: "2010-09-09"
Description: "Launch CI-Create-ChangeSet-demo"
    
    
# ------------------------------------------------------------
#  Metadate
# ------------------------------------------------------------
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Parameters:
          - PJPrefix
          - CIDRVpc
          - CIDRPublicSubnetA
          - CIDRPublicSubnetC
          - CIDRPrivateSubnetA
          - CIDRPrivateSubnetC
          
          
# ------------------------------------------------------------
# Input Parameters
# ------------------------------------------------------------
Parameters:
### Project Prefix ###
  PJPrefix:
    Type: String
### VPC ###
  CIDRVpc:
    Type: String
### Public Subnet ###
  CIDRPublicSubnetA:
    Type: String
  CIDRPublicSubnetC:
    Type: String
### Private Subnet ###
  CIDRPrivateSubnetA:
    Type: String
  CIDRPrivateSubnetC:
    Type: String
    

### Resources ###
Resources: 
# ------------------------------------------------------------
# VPC
# ------------------------------------------------------------
  VPC: 
    Type: "AWS::EC2::VPC"
    Properties: 
      CidrBlock: !Ref CIDRVpc
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      InstanceTenancy: default
      Tags: 
        - Key: Name
          Value: !Sub "${PJPrefix}-VPC"
          
          
# ------------------------------------------------------------
# InternetGateway:
# ------------------------------------------------------------
  InternetGateway: 
    Type: "AWS::EC2::InternetGateway"
    Properties: 
      Tags: 
        - Key: Name
          Value: !Sub "${PJPrefix}-IGW"
          
  IGWAttachment: 
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties: 
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
          
          
# ------------------------------------------------------------
# NatGateway
# ------------------------------------------------------------
### NAT Gateway ###
  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - NatGatewayEIP
          - AllocationId
      SubnetId: !Ref PublicSubnetA
      Tags:
        - Key: Name
          Value: !Sub "${PJPrefix}-NAT-Gateway"
          
### NAT Gateway EIP ###
  NatGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub "${PJPrefix}-NGW-EIP" 
          
          
# ------------------------------------------------------------
# Subnet
# ------------------------------------------------------------
### Public Subnet ###
  PublicSubnetA:
    Type: "AWS::EC2::Subnet"
    Properties: 
      AvailabilityZone: "ap-northeast-1a"
      CidrBlock: !Ref CIDRPublicSubnetA
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub "${PJPrefix}-PublicSubnet-A"
          
  PublicSubnetC:
    Type: "AWS::EC2::Subnet"
    Properties: 
      AvailabilityZone: "ap-northeast-1c"
      CidrBlock: !Ref CIDRPublicSubnetC
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub "${PJPrefix}-PublicSubnet-C"
          
### Private Subnet ###
  PrivateSubnetA:
    Type: "AWS::EC2::Subnet"
    Properties: 
      AvailabilityZone: "ap-northeast-1a"
      CidrBlock: !Ref CIDRPrivateSubnetA
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub "${PJPrefix}-PrivateSubnet-A"
          
  PrivateSubnetC:
    Type: "AWS::EC2::Subnet"
    Properties: 
      AvailabilityZone: "ap-northeast-1c"
      CidrBlock: !Ref CIDRPrivateSubnetC
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub "${PJPrefix}-PrivateSubnet-C"
          
          
# ------------------------------------------------------------
# RouteTable
# ------------------------------------------------------------
### PublicSubnetA Routing ###
  RTBPublicA: 
    Type: "AWS::EC2::RouteTable"
    Properties: 
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub "${PJPrefix}-PublicRouteA"
          
  RTBAssociationPublicA: 
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties: 
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref RTBPublicA
      
  RoutePublicA01: 
    Type: "AWS::EC2::Route"
    Properties: 
      RouteTableId: !Ref RTBPrivateA
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway
      
### PublicSubnetC Routing ###
  RTBPublicC: 
    Type: "AWS::EC2::RouteTable"
    Properties: 
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub "${PJPrefix}-PublicRouteC"
          
  RTBAssociationPublicC: 
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties: 
      SubnetId: !Ref PublicSubnetC
      RouteTableId: !Ref RTBPublicC
      
  RoutePublicC01: 
    Type: "AWS::EC2::Route"
    Properties: 
      RouteTableId: !Ref RTBPrivateC
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway
      
### PrivateSubnetA Routing ###
  RTBPrivateA: 
    Type: "AWS::EC2::RouteTable"
    Properties: 
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub "${PJPrefix}-PrivateRouteA"
          
  RTBAssociationPrivateA: 
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties: 
      SubnetId: !Ref PrivateSubnetA
      RouteTableId: !Ref RTBPrivateA
      
  RoutePrivateA01: 
    Type: "AWS::EC2::Route"
    Properties: 
      RouteTableId: !Ref RTBPublicA
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref NatGateway
      
### PrivateSubnetC Routing ###
  RTBPrivateC: 
    Type: "AWS::EC2::RouteTable"
    Properties: 
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub "${PJPrefix}-PrivateRouteC"
          
  RTBAssociationPrivateC: 
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties: 
      SubnetId: !Ref PrivateSubnetC
      RouteTableId: !Ref RTBPrivateC
      
  RoutePrivateC01: 
    Type: "AWS::EC2::Route"
    Properties: 
      RouteTableId: !Ref RTBPublicC
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref NatGateway
      
      
# ------------------------------------------------------------
# Output Parameter
# ------------------------------------------------------------
Outputs:
### VPC ###
  VPC:
    Value: !Ref VPC
      
### Subnet ###
  PublicSubnetA:
    Value: !Ref PublicSubnetA
  PublicSubnetC:
    Value: !Ref PublicSubnetC
  PrivateSubnetA:
    Value: !Ref PrivateSubnetA
  PrivateSubnetC:
    Value: !Ref PrivateSubnetC